#ifndef MESSAGEHANDLER
#define MESSAGEHANDLER

#include <SFML/Network.hpp>
#include <iostream>
#include <string>
#include <vector>
#include <queue>

//THIS CLASS WILL RUN BETWEEN THE USER AT THE COMMAND LINE AND THE NETWORK SOCKET CONNECTION CONCURRENTLY,
//THIS WAY THE USER CAN COMMUNICATE WITH THE PROGRAM WITH A CLI WHILE THE CONNECTION RUNS IN THE BACKGROUND
class MessageHandler{

    public:

      //THIS FUNCTION WILL RECIEVE AND SEND COMMAND LINE MESSAGES TO THE USER IN ITS OWN THREAD
      void CLI();

    private:

      //THIS FUNCTION WILL RECIEVE AND SEND MESSAGES BETWEEN THE CLI PROGRAM AND THE SOCKET CONNECTION
      void Perform();

      //THIS VECTOR STORES A STACK OF MESSAGES BETWEEN THE USER AND THE PROGRAM
      std::vector<std::map< std::string, std::string>>;

};

#endif // STRING_LOADER_H
